### ISSUE TITLE
New Calendar Endpoint for Promotional Homepage

### ISSUE THREAD

**Issue by anlumo** [Metalab/mos#141]
We need an endpoint for returning a list of the next 5 events (starting on midnight of the same day, so currently active events should also be visible) with the #136 flag set.

The format should be JSON with the following format:

```json
[
    {
        "date": "Wed 30.11.2022 18:00 - 22:00",
        "title": "Define Jugend Workshop 4",
        "url": "https://metalab.at/wiki/Define",
        "subtitle": "Zugang für blinde und sebehinderte Menschen zum metalab"
    },
    {
        "date": "Wed 30.11.2022 19:00 - 23:00",
        "title": "3D-Drucker Workshop",
        "url": "https://metalab.at/wiki/3d_printer_workshop",
        "subtitle": null
    },
    ...
]
```

The array should be sorted by starting time.

**Comment by Hetti** [comment]
pr is merged :+1:

**Comment by ralokt** [comment]
Will do it as specified now in the interest of launching the new HP soon, but some suggested changes/refactors for later:
 - Instead of sending a free-format `"date"`, it would be cleaner to send back `"startDate"` and `"endDate"` in isoformat, and let the frontend decide how to render that.
 - The number of events to fetch should maybe be a GET parameter instead of being hardcoded to `5`.
 - We should make an effort to keep names of things consistent between FE, API and BE where fields correspond to one another. Here that would mean renaming `"subtitle"` to `"teaser"` (and keeping the camel case for the date fields specified above).
 
All of this applies in particular if this isn't a one-off and we wanna start building an API. Also, I'm gonna do this in vanilla Django for now, but if we wanna do that, we should think about maybe using something like DRF.

**Comment by ralokt** [comment]
Also, I'm gonna take the liberty to extend the specification of the format for `"date"` - multi-day events will get a `" (+n)"` added to the end. So, for example `"Fri 25.11.2022 18:30 - 18:30 (+2)"` for the hackathon :)
